spring:
  application:
    name: travel
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/travel
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml

server:
  error:
    include-message: always
  port: 9900
  url: http://localhost:9900